---
title: "1-intro"
output: pdf_document
---

# Introduction

Spatio-temporal data has a spatial component referring to the location of each observation and a temporal component that is recorded at regular or irregular time intervals. It may also include multiple variables measured at each spatial and temporal values. With spatio-temporal data, one can fix the time to explore the spatial features of the data, fix the spatial location/s to explore temporal aspects, or dynamically explore the space and time simultaneously. 

In order to computationally explore the spatial, temporal and spatio-temporal faces of such data, the data needs to be stored and represented under a specific data object that allows the user to query, group and dissect all the data faces.

The Comprehensive \proglang{R} Archive Network (CRAN) task view SpatioTemporal [@ctvspatiotemporal] gathers information about \proglang{R} packages designed for spatio-temporal data and it has a section on *Representing data* that lists existing spatio-temporal data representations used in \proglang{R}. Among them, @spacetime summarises spatio-temporal data into three forms: time-wide, space-wide, and long formats. The associated package \pkg{spacetime} [@spacetime] implements four spatio-temporal layouts (full grid, sparse grid, irregular, and trajectory) to handle different space and time combinations. The package \pkg{stars} [@stars] has a new implementation to use dense arrays to represent spatio-temporal cubes. It also interfaces with the package \pkg{sf} [@sf], commonly used for wrangling spatial data, and the \pkg{tidyverse} [@tidyverse] suite for general data wrangling and visualization in \proglang{R}.

Still, the data representation for spatio-temporal data can be further extended and there are two reasons for this. Firstly, the raw data sourced in the wild is less often presented in any one of the layouts above, and fitting the raw data into a data object can sometimes be difficult. More often, spatio-temporal data are collected in separate 2D tables and analysts need to assemble them into a whole piece before exploring the data. Examples of components of spatio-temporal data can be 1) areal data recording the shape of a collection of areas of interest; 2) geostatistical data storing the longitude and latitude coordinates of locations, typically also with other metadata related to the location, and; 3) temporal data of each location across time.

The other reason is about tidy data concepts [@tidydata] and how they should be applied to spatio-temporal data. According to the tidy data principles, data should be structured into 1) one row per observation, 2) one column per variable, and 3) one type of data per table. The long form data is preferred over wide data form given the downstream packages such as \pkg{dplyr} [@dplyr] and \pkg{ggplot2} [@ggplot2] for data wrangling and visualization. However, the long form can be inefficient to store feature geometries, especially for large multipolygons for hourly, daily or sub-daily periods over years, which are extensively collected and handled, for example in time series analysis. This poses the question of how to arrange spatial and temporal variables in a way that would make data wrangling, visualizing and analyzing spatio-temporal data easier.

This paper presents a new \proglang{R} package, \pkg{cubble}, which addresses the two issues mentioned above. In the package, a new class, also called cubble, is proposed to organize spatial and temporal variables as two forms of a single data object so that they can be wrangled separately or combined while being kept synchronized. Among the four spacetime layouts in @spacetime, the \code{cubble} class can be applied to full grid, sparse grid, or irregular, but not trajectory, which is outside the scope of this work. The software is available from the Comprehensive \proglang{R} Archive Network (CRAN) at https://CRAN.R-project.org/package=cubble. 

The rest of the paper is organized as follows: Section \@ref(cube) introduces the proposed cube structure as a way to conceptualize multivariate spatio-temporal data. Section \@ref(cubble) presents the main design and functionality of the \pkg{cubble} package. Section \@ref(others) explains how the \pkg{cubble} package deals with more advanced considerations, including data with hierarchical structure, data matching and how the package fits with existing static and interactive visualization tools. Moreover we also illustrate how the \pkg{cubble} package deals with spatio-temporal data transformations. Section \@ref(examples) uses Australian weather station data and river level data as examples to demonstrate the use of the package. An example of how the \pkg{cubble} package handles Network Common Data Form (NetCDF) data is also provided. Section \@ref(conclude) discuss the paper contributions and future directions.


<!-- Manipulating data in these two levels is usually done separately and the third tidy data principal [@tidydata] recommends each type of observational unit to form a table. Another feature for a spatio-temporal data structure to have is that variables created from subsequent operations can be automatically added to the existing table with the same level. This is better than an output that index the variables with the identifiers since otherwise analysts will need to manually join this output with existing variables in the same level. -->

<!-- Many data structures have been proposed for spatial (\pkg{sf} by @sf) and temporal (\pkg{tsibble} by @tsibble) data in the R community, while less has been done for spatio-temporal data. The lack of such tools could potentially because analysts usually treat the spatial and temporal dimension of the data separately, without realising the need to create a new data structure. While this approach follows the third tidy data principal [@tidydata] (*Each type of observational unit forms a table*), analysts always need to manually join results from different observational units or combining multiple tables into one for downstream analysis. This additional step doesn't add new operations into the data but can be error prone. \newline -->

<!-- While incorporating both spatial and temporal information enriches the data in the analysis, spatio-temporal data can sometimes be hard to work with given its two observational units in the variables. The single table format in Figure \ref{fig:illu-input} is convenient for spatio-temporal operations that involve both types of variables, however, it makes duplicates of spatial variables and is not ideal when only looking at the spatial aspect of the data. The two tables format allows separate operations on spatial and temporal variables while analysts need to work with two data objects simultaneously and join them together into the single table format for spatio-temporal operations. Neither of the two formats is desirable at the same time for spatial, temporal, and spatio-temporal operations. This issue implies analysts need to constantly think about the data format and arrange variables into the proper shape before the actual operations, which can be a laborious step when switching between the two formats back and forth several times during the analysis. -->

<!-- This would require analysts to constantly switch among different format at each step. All these difficulties are rooted in the two different observational units of spatial and temporal variables and this poses difficulties to organise spatio-temporal data in a way that operates both on a single spatial or temporal dimension and the combined spatio-temporal dimension. -->

<!-- None of these three formats in Figure \ref{fig:illu-input} is not particularly convenient to work with. In the single table format, to avoid plotting duplicated points of the same sites on the map, analysts always need to create a spatial variables table from the original single table. This can be a tedious step if needs to performed many times during the analysis. In another type of operation that filter the sites based on certain statistics, intermediate objects, like the per-station summary of the statistic and the filtered station ID vector, will need be created as standalone objects in the environment. The spirit of using pipe reduces the intermediate data objects that are unnecessarily created in the analysis while in this case, these only-used-once data objects can hardly be incorporated into a piping workflow in the analysis. In addition, if the data is organised as a separate spatial and temporal table as format 2 in Figure \ref{fig:illu-input}, the filter on site ID will need to performed twice in each table to keep them both up-to-date. With the array data structure, although it can easily store and wrangle large spatio-temporal data, the 3D or higher-D array can be less intuitive than a 2D tabular data structure for some analysts in data wrangling. -->



<!-- The package \pkg{sf} [@sf] uses data frame objects to represent spatial data with an additional \code{geometry} column dedicating to feature geometries [@jr_herring_opengis_2011] (e.g. POINT, MULTIPOINT, POLYGON, MULTIPOLYGON etc).  -->

<!-- For temporal data, \pkg{tsibble} [@tsibble] builds on top of the \pkg{tibble} [@tibble] object and explicitly includes date and time in columns as variables, rather than data attributes.  -->

<!-- Underlying tidyverse is the concept of tidy data [@tidydata], which considers how variables should be structured for analysis. In the three formats (time-wide, space-wide, and long) summarised in the @spacetime paper, only the long form is considered as tidy. The main advantages of it over the time-wide and space-wide format is that the latter treat either time or location as variable names (Section 3.1 in @tidydata) rather than values of variables, making them difficult to be wrangled. One problem with the long format is that it can be inefficient to store feature geometries, especially for large MULTIPOLYGON over long time period.  -->

<!-- For spatial data, \pkg{sf} [@sf] covers a wide range of geometrical operations and is the format most map data stored. When incorporating the time dimension, a time wide format, introduced in @spacetime, is usually adopted. This treats time as variable name rather than value and makes it inconvenient to wrangle time, as per the tidy data principle [@tidydata]. In the temporal domain, \pkg{tsibble} [@tsibble] follows the tidy data principle to arrange the time in the long format, while when adding spatial variables, a long format implies repeating variables at each time and this can make a huge difference when the repetition is on large geometrical shapes with long time period.  -->

<!-- In the \proglang{R} community, many data objects have been proposed to work with specific spatio-temporal tasks, while few can freely explore the data. \pkg{spacetime} [@spacetime] is an attempt for such a data object, but the spatial and temporal classes it is built on have now been gradually replaced by more recent implementations. The \pkg{stars} [@stars] package uses an array to wrangle spatio-temporal data, but the dense array it uses can quickly exhaust the memory for data in the case of irregular spatial grid. -->
