---
documentclass: jss
classoption: shortnames
author:
  - name: H. Sherry Zhang
    affiliation: Monash University
    address: 21 Chancellors Walk, Clayton VIC 3800 Australia
    email: \email{huize.zhang@monash.edu}
  - name: Dianne Cook
    affiliation: 'Monash University \AND'
    address: 21 Chancellors Walk, Clayton VIC 3800 Australia
    email: dicook@monash.edu
  - name: Ursula Laa
    affiliation: 'University of Natural Resources and Life Sciences \AND'
    address: Gregor-Mendel-Straße 33, 1180 Wien, Austria
    email:  ursula.laa@boku.ac.at
  - name: Nicolas Langrené
    affiliation: 'BNU-HKBU United International College'
    address: 2000 Jintong Road, Tangjiawan, Zhuhai, Guangdong Province, China
    email: nicolaslangrene@uic.edu.cn
  - name: Patricia Menéndez
    affiliation: 'Monash University'
    address: 21 Chancellors Walk, Clayton VIC 3800 Australia
    email:  patricia.menendez@monash.edu
title:
  formatted: "\\pkg{cubble}: An \\proglang{R} Package for Organizing and Wrangling Multivariate Spatio-temporal Data"
  # If you use tex in the formatted title, alsoge supply version without
  plain:     "cubble: An R Package for Organizing and Wrangling Multivariate Spatio-temporal Data"
  # For running headers, if needed
  # short:     "\\pkg{foo}: A Capitalized Title"
abstract: >
     Multivariate spatio-temporal data refers to multiple measurements taken across space and time. For many analyses, spatial and time components can be separately studied: for example, to explore the temporal trend of one variable for a single spatial location, or to model the spatial distribution of one variable at a given time. However for some studies, it is important to analyze different aspects of the spatio-temporal data simultaneously, like for instance, temporal trends of multiple variables across locations. In order to facilitate the study of different portions or combinations of spatio-temporal data, we introduce a new class, \code{cubble}, with a suite of functions enabling easy slicing and dicing on the different components spatio-temporal components.  The proposed \code{cubble} class ensures that all the components of the data are easy to access and manipulate while providing flexibility for data analysis. In addition, the \pkg{cubble} package facilitates visual and numerical explorations of the data while easing data wrangling and modelling. The \code{cubble} class and the functions provided in the \pkg{cubble} \proglang{R} package equip users with the capability to handle hierarchical spatial and temporal structures. The \code{cubble} class and the tools implemented in the package are illustrated with different examples of Australian climate data.
keywords:
  # at least one keyword must be supplied
  formatted: [spatial, temporal, spatio temporal, "\\proglang{R}", environmental data, exploratory data analysis]
  plain:     [spatial, temporal, spatio temporal, R, environmental data, exploratory data analysis]
preamble: >
  \usepackage{amsmath}
  \usepackage{array}
  \usepackage{xcolor}
  \newcommand{\sherry}[1]{\textcolor{magenta}{#1}}
output: 
  bookdown::pdf_book:
    base_format: rticles::jss_article
bibliography: ../references.bib
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  cache = TRUE,
  fig.path = here::here("figures/")
)

options(prompt = "R> ", continue = "+ ",
        tibble.print_max = 5, tibble.print_min = 5,
        width = 70, styler.cache_root = "styler-perm")
```

```{r echo = FALSE}
library(cubble)
library(tidyverse)
library(patchwork)
```

\newpage 

```{r child = here::here("1-intro.Rmd")}

```

```{r child = here::here("2-cube.Rmd")}

```

```{r child = here::here("3-the-cubble-pkg.Rmd")}

``` 

```{r child = here::here("4-other-features.Rmd")}

```

```{r child = here::here("5-1-covid.Rmd")}

```

```{r child = here::here("5-2-aus-hist-max-temp.Rmd")}

```


```{r child = here::here("5-3-river-level-rainfall.Rmd")}

```


```{r child = here::here("5-4-era5.Rmd")}

```

```{r child = here::here("5-5-interactive-graphics.Rmd")}

```


```{r child = here::here("6-conclusion.Rmd")}

```
