---
title: A template for the *arxiv* style
authors:
  - name: H.Sherry Zhang
    department: Department of Econometrics and Business Statistics 
    affiliation: Monash University 
    location: Melbourne, Australia
    email:  huize.zhang@monash.edu
  - name: Dianne Cook
    department: Department of Econometrics and Business Statistics 
    affiliation: Monash University 
    location: Melbourne, Australia
    email:  dicook@monash.edu
  - name: Ursula Laa
    department: Institute of Statistics
    affiliation: University of Natural Resources and Life Sciences
    location: Vienna, Austria
    email:  ursula.laa@boku.ac.at  
  - name: Nicolas Langrené
    department: 34 Village Street, Docklands VIC 3008 Australia
    affiliation: CSIRO Data61 
    location: Melbourne, Australia
    email: nicolas.langrene@csiro.au
  - name: Patricia Menéndez
    department: Department of Econometrics and Business Statistics 
    affiliation: Monash University 
    location: Melbourne, Australia
    email:  patricia.menendez@monash.edu 
abstract: |
  Enter the text of your abstract here.
keywords:
  - blah
  - blee
  - bloo
  - these are optional and can be removed
bibliography: references.bib
biblio-style: unsrt
output: rticles::arxiv_article
---

# Introduction

Spatio-temporal data record changes of variables [for a reasonable length of period and spread across geographical region]. In this article, we consider spatio-temporal vector data, which are recorded in a fixed interval and are point based, characterised by longitude and latitude, in the spatial aspect. Examples of this type of data include the house price of a city or county, climate measures from weather stations in a country, and river level data from electronic gauges. 

Analysing this type of data requires less considerations on the geographical geometry type and map projection but more on how measures in these fixed locations changes across the time domain and whether these changes are related for adjacent locations. For example, when nearby areas show patterns that are regular enough, visualising spatio-temporal data can 1) discover regional time series features, i.e. trend and seasonality, 2) find the Waldo sites from the crowd, and 3) see how correlation of nearby sites changes across time. 

The main difficulty in visualising this type of data is to show information in both space and time dimension with the proper level of details without information overflow. This would sometimes require aggregating the time dimension into the proper level or slicing the data into a reasonable number of subset for display. In this sense, a data structure that regulates the manipulation spatio-temporal data will benefit the analysis workflow. While many implementations focus on manipulating and visualising pure spatial or temporal data, there are not sufficient tools to deal with spatio-temporal data. The purpose of this paper is to introduce a spatio-temporal vector data structure for data analysis in R. 

The rest of the paper will be divided as follows: Section 2 reviews the existing data structure for spatio, temporal, and spatio-temporal data. Section 3 presents a new data structure for spatio-temporal data: cubble. Then the paper introduces the workflow of data manipulation and visualisation with the cubble structure in Section 4. Section 5 gives some examples on how common spatial and temporal manipulations are performed with cubble and how static and interactive visualisation help to understand climate and [...] data.

# Existing data structure for spatio and temporal data

There has been a large class of implementations dedicated to processing the spatial data. This includes `sf` [@pebesma2018simple] and its precedent `sp` [@pebesma2005s] for ... and `raster` [@raster] and `terra` [@terra] for raster data. While these implementations specialised in geographic manipulations with different type of simple features, it doesn't incorporate a temporal dimension in the data structure. Project like `stars` [@stars] and `spacetime` [@spacetimebook] by R-Spatial allows for both space and time dimension for raster and vector data, but the underlying data structure is a multi-dimensional array, which could be difficult to operate for R users who are more familiar with the operation in 2D dataframe/ tibble.

<!-- - `sp` + `spacetime` (time series data from package `xts`) -->

<!-- - `sf`  -->
<!--   - simple features geometry  -->
<!--   - only spatio -->
<!--   - good for geographical but these geometry types i.e. multipolygon, can be hard to manipulate. Would be nice to have a vector data structure -->

<!-- - `stars` -->
<!--   - a newer structure allow both spatio + temporal  -->
<!--   - array -->

In the temporal aspect, the `tsibble` [@tsibbles] structure and its tidyverts ecosystem have provided a [... ] workflow to work with temporal data. In a tsibble structure, temporal data is characterised by `index` and `key` where `index` is the temporal identifier and `key` is the identifier for multiple series, which could be used as a spatio identifier. However, a tsibble object, by construction, always requires the `index` in its structure. This makes it less appealing for spatio-temporal data since the output of calculated spatio-specific variables (i.e. features of each series) don't have the time dimension. Analysts will either need to have an additional step to join this output to the original tsibble or operate with variables stored in two separate objects. In addition, the long form structure of a tsibble object means spatio variables (i.e. longitude, latitude, and features of each series if joined back to the tsibble) of each spatio identifier will be repetitively recorded at each timestamp. This repetition is unnecessary and would inflate the object size for long series.

# A new data structure for spatio-temporal data

Intro to cubble: 

- list-column: rowwise_df with temporal variables, including the time index, nested. 
  - Focus on spatio: those output per station

- long form: grouped_df 
  - Focus on temporal

Compatible with tidyverse manipulation and tsibble

# Manipulation and visualisation with `cubble`

Mention different types of manipulation with cubble:
  
  - `dplyr` support for cubble: 
    - basic 5s: mutate, filter, summarise, select, arrange
    - group and ungroup: group_by, ungroup
    - slice family
  - summarise missing stats

# Examples

Daily climate data (prcp, tmax, and tmin) from RNOAA - lots of stations across Australia

An exploratory data analysis questions: What's the climate profile look like in Australia

  - General features: Any general trend/ fluctuation in prcp, tmax, and tmin?
  - Local features: Any station stands out from the crowd?

## Manipulation

  - data quality check: filter out stations have variables not properly recorded 
  - data summary: 
    - daily -> monthly/ weekly, 
    - summarise by mean for tmax/ tmin, sum for prcp
  - 

## Graphics

Static + interactive -> tooltip to show additional information upon hovering

  - Where are those stations on the map? 
    - Mention mostly aero, airport, and lighthouse

# Summary