---
title: "Wrangling multivariate spatio-temporal data with the R package cubble"
authors:
  - name: H. Sherry Zhang
    affiliation: Monash University
    location: 21 Chancellors Walk, Clayton VIC 3800 Australia
    email: huize.zhang@monash.edu
  - name: Dianne Cook
    affiliation: Monash University
    location: 21 Chancellors Walk, Clayton VIC 3800 Australia
    email: dicook@monash.edu
  - name: Ursula Laa
    affiliation: University of Natural Resources and Life Sciences
    location: Gregor-Mendel-Straße 33, 1180 Wien, Austria
    email:  ursula.laa@boku.ac.at
  - name: Nicolas Langrené
    affiliation: BNU-HKBU United International College
    location: 2000 Jintong Road, Tangjiawan, Zhuhai, Guangdong Province, China
    email: nicolaslangrene@uic.edu.cn
  - name: Patricia Menéndez
    affiliation: Monash University
    location: 21 Chancellors Walk, Clayton VIC 3800 Australia
    email:  patricia.menendez@monash.edu
abstract: |
    Multivariate spatio-temporal data refers to multiple measurements taken across space and time. For many analyses, spatial and time components can be separately studied: for example, to explore the temporal trend of one variable for a single spatial location, or to model the spatial distribution of one variable at a given time. However for some studies, it is important to analyse different aspects of the spatio-temporal data simultaneouly, like for instance, temporal trends of multiple variables across locations. In order to facilitate the study of different sections or combinations of spatio-temporal data, we introduce a new data structure, \code{cubble}, with a suite of functions enabling easy slicing and dicing on the different components spatio-temporal components, for visual and numerical explorations while facilitating data wrangling for modelling. The proposed \code{cubble} structure ensures that all the components of the data are easy to access and manipulate while providing flexibility for data analysis. The \code{cubble} structure and the tools provided in the \code{cubble} R package equip users with the capability to handle hierarchical spatial and temporal structures. The tools are illustrated with examples of Australian climate data, merging climate and river level data sources, reproducing a climate reanalysis (ERA5), and creating interactive graphics.
keywords:
- spatial, temporal, spatio temporal, R, exploratory data analysis, environmental data, climate data
bibliography: "../references.bib"
cls: "../jss.cls"
bst: "../jss.bst"
preamble: |
  \newcommand{\sherry}[1]{\textcolor{magenta}{#1}}
output:
  bookdown::pdf_book:
    base_format: rticles::arxiv_article
link-citations: true
---
```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  cache = TRUE,
  fig.path = here::here("figures/"),
  fig.height = 10,
  root.dir = here::here()
)
options(prompt = "R> ", continue = "+ ",
        tibble.print_max = 5, tibble.print_min = 5)
```

```{r}
library(cubble)
library(dplyr)
```


\newpage

```{r child = here::here("1-intro.Rmd")}

```

```{r child = here::here("2-0-cube.Rmd")}

```


```{r child = here::here("2-the-cubble-pkg.Rmd")}

```

```{r child = here::here("3-advanced.Rmd")}

```

```{r child = here::here("4-1-basic.Rmd")}

```

```{r child = here::here("4-2-agg.Rmd")}

```


```{r child = here::here("4-3-water-level.Rmd")}

```


```{r child = here::here("4-4-netcdf.Rmd")}

```

```{r child = here::here("4-5-interactive.Rmd")}

```


```{r child = here::here("5-conclusion.Rmd")}

```
